version: "3.3"  # optional since v1.27.0
services:
  web:
    build: ./docker-node
    ports:
      - "3000:3000"
    volumes:
      - ./docker-node:/home
      
  web-r:
    build: ./docker-r
    ports:
      - "2000:2000"
      - "5000:5000"
      
    volumes:
      - ./docker-r:/home
      
  rabbitmq:
    image: rabbitmq
    
  rabbitmq3: # (for debugging)
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express: # (for debugging)
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example # (for development)
    

